version: '3.8'

services:
  flask-app:
    build: .
    image: "auth-app:${IMAGE_TAG:-1}" # ‚Üê Tags with your version
    container_name: python-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=flask_db
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  mysql:
    image: sayedshahrukh93/mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=flask_db
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./AuthApp/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
